### ISSUE TITLE
html syntax autocomplete?

### ISSUE THREAD

**Issue by YnotProgramInSwift** [franciscoamado/vscode-html-leaf#2]
Not sure whether this is the right place to ask this question, but I installed this extension in vscode last night and the IDE does not autocomplete HTML tags. Is that a built in feature of this extension? (sorry if this is a dumb question. I have always only used xcode.) Cheers, Tony

**Comment by franciscoamado** [comment]
Hey there! 

Sorry to have missed this.

This plugin doesn't have autocomplete of HTML tags.

For that I recommend using the [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) plugin. It works really great.

Cheers,
Francisco

**Comment by YnotProgramInSwift** [comment]
Awesome! thank you.
