### ISSUE TITLE
Leaf 4 support

### ISSUE THREAD

**Issue by joltguy** [franciscoamado/vscode-html-leaf#3]
[Leaf 4](https://docs.vapor.codes/4.0/leaf/overview/#template-syntax) has introduced new syntax that is not being recognized by the highlighter. Some examples: `#endif`, `#endfor`, `#endexport`, `#endextend`.

The `if` structure has also changed to:
```html
#if (condition):
    <!-- something -->
#else:
    <!-- something else -->
#endif
```

**Comment by franciscoamado** [comment]
Hey @joltguy 👋🏻 

Sorry for taking so long and thanks for warning me about this!

I've updated this extension to support Leaf 4.

Hope it helps your development!

**Comment by joltguy** [comment]
That's great, thanks!!

**Comment by alobaili** [comment]
@franciscoamado Thanks for the update! How to install this extension in VS Code?
